<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de" sourcelanguage="en">
  <context>
    <name>AddonsInstaller</name>
    <message>
      <location filename="install_to_toolbar.py" line="76"/>
      <source>Create new toolbar</source>
      <translation>Neue Symbolleiste erstellen</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="219"/>
      <source>A macro installed with the FreeCAD Addon Manager</source>
      <translation>Ein Makro, das mit dem FreeCAD Addon Manager installiert wurde</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="221"/>
      <source>Run</source>
      <comment>Indicates a macro that can be &apos;run&apos;</comment>
      <translation>Ausführen</translation>
    </message>
    <message>
      <location filename="package_details.py" line="112"/>
      <source>Version {version} installed on {date}</source>
      <translation>Version {version} installiert am {date}</translation>
    </message>
    <message>
      <location filename="package_details.py" line="117"/>
      <source>Version {version} installed</source>
      <translation>Version {version} wurde installiert</translation>
    </message>
    <message>
      <location filename="package_details.py" line="121"/>
      <source>Installed on {date}</source>
      <translation>Installationsdatum: {date}</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="567"/>
      <source>Installed</source>
      <translation>Installiert</translation>
    </message>
    <message>
      <location filename="package_details.py" line="96"/>
      <source>Version</source>
      <translation>Version</translation>
    </message>
    <message>
      <location filename="package_details.py" line="103"/>
      <source>Unknown version (no package.xml file found)</source>
      <translation>Unbekannte Version (keine Datei package.xml gefunden)</translation>
    </message>
    <message>
      <location filename="package_details.py" line="108"/>
      <source>installed on</source>
      <translation>installiert auf</translation>
    </message>
    <message>
      <location filename="package_details.py" line="118"/>
      <source>installed</source>
      <translation>installiert</translation>
    </message>
    <message>
      <location filename="package_details.py" line="126"/>
      <source>Update available to version</source>
      <translation>Update verfügbar für Version</translation>
    </message>
    <message>
      <location filename="package_details.py" line="144"/>
      <source>This is the latest version available</source>
      <translation>Dies ist die neueste verfügbare Version</translation>
    </message>
    <message>
      <location filename="package_details.py" line="151"/>
      <source>Updated, please restart FreeCAD to use</source>
      <translation>Aktualisiert, bitte FreeCAD zur Nutzung neu starten</translation>
    </message>
    <message>
      <location filename="package_details.py" line="159"/>
      <source>Update check in progress</source>
      <translation>Aktualisierungsprüfung läuft</translation>
    </message>
    <message>
      <location filename="package_details.py" line="163"/>
      <source>Automatic update checks disabled</source>
      <translation>Automatische Aktualisierungsprüfungen deaktiviert</translation>
    </message>
    <message>
      <location filename="package_details.py" line="172"/>
      <source>Installation location</source>
      <translation>Installationsort</translation>
    </message>
    <message>
      <location filename="package_details.py" line="240"/>
      <source>WARNING: This addon is obsolete</source>
      <translation>WARNUNG: Dieses Addon ist veraltet</translation>
    </message>
    <message>
      <location filename="package_details.py" line="250"/>
      <source>WARNING: This addon is Python 2 Only</source>
      <translation>WARNUNG: Dieses Addon ist nur für Python 2 geeignet</translation>
    </message>
    <message>
      <location filename="package_details.py" line="312"/>
      <source>Fetching README.md from package repository</source>
      <translation>README.md aus dem Paket-Repository abrufen</translation>
    </message>
    <message>
      <location filename="package_details.py" line="354"/>
      <source>WARNING: This addon requires FreeCAD </source>
      <translation>WARNUNG: Dieses Addon benötigt FreeCAD </translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="431"/>
      <source>Delete cached version of this README and re-download</source>
      <translation>
        <numerusform>Lösche die zwischengespeicherte Version dieses READMEs und lade sie erneut herunter</numerusform>
        <numerusform>Lösche zwischengespeicherte Version dieser README und lade sie erneut herunter</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_details.py" line="510"/>
      <source>No URL or wiki page provided by this macro</source>
      <translation>Keine URL oder Wiki-Seite von diesem Makro bereitgestellt</translation>
    </message>
    <message>
      <location filename="package_details.py" line="563"/>
      <source>Could not load README data from URL {}</source>
      <translation>Konnte die README-Daten nicht von URL {} laden</translation>
    </message>
    <message>
      <location filename="package_details.py" line="577"/>
      <source>Success</source>
      <translation>Erfolgreich</translation>
    </message>
    <message>
      <location filename="package_details.py" line="600"/>
      <source>Changed to git ref &apos;{}&apos; -- please restart to use Addon.</source>
      <translation>Wechsel zu git ref  &apos;{}&apos; -- bitte neu starten um die Erweiterung zu nutzen.</translation>
    </message>
    <message>
      <location filename="package_details.py" line="636"/>
      <source>Page JavaScript reported</source>
      <translation>JavaScript-Seite gemeldet</translation>
    </message>
    <message>
      <location filename="package_details.py" line="407"/>
      <source>Install</source>
      <translation>Installieren</translation>
    </message>
    <message>
      <location filename="package_details.py" line="410"/>
      <source>Uninstall</source>
      <translation>Deinstallieren</translation>
    </message>
    <message>
      <location filename="package_details.py" line="413"/>
      <source>Update</source>
      <translation>Aktualisieren</translation>
    </message>
    <message>
      <location filename="package_details.py" line="416"/>
      <source>Check for Update</source>
      <translation>Auf Aktualisierung prüfen</translation>
    </message>
    <message>
      <location filename="package_details.py" line="419"/>
      <source>Run Macro</source>
      <translation>Makro ausführen</translation>
    </message>
    <message>
      <location filename="package_details.py" line="786"/>
      <source>Change Branch</source>
      <translation>Git-Branch wechseln</translation>
    </message>
    <message>
      <location filename="package_details.py" line="867"/>
      <source>Enable</source>
      <translation>Aktivieren</translation>
    </message>
    <message>
      <location filename="package_details.py" line="870"/>
      <source>Disable</source>
      <translation>Deaktivieren</translation>
    </message>
    <message>
      <location filename="package_details.py" line="424"/>
      <source>Return to package list</source>
      <translation>Zurück zur Paketliste</translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="800"/>
      <source>QtWebEngine Python bindings not installed -- using fallback README display. See Report View for details and installation instructions.</source>
      <translation type="unfinished">
        <numerusform>QtWebEngine Python ist nicht installiert -- Benutze bitte die alternative vom README. Details und Installationsanweisungen sind im Ausgabefenster zu finden.</numerusform>
        <numerusform>QtWebEngine Python bindings not installed -- using fallback README display. See Report View for details and installation instructions.</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_list.py" line="119"/>
      <source>Filter is valid</source>
      <translation>Filter ist gültig</translation>
    </message>
    <message>
      <location filename="package_list.py" line="125"/>
      <source>Filter regular expression is invalid</source>
      <translation>RegEx Filter ist ungültig</translation>
    </message>
    <message>
      <location filename="package_list.py" line="207"/>
      <source>Click for details about package {}</source>
      <translation>Für Details zum Paket {} klicken</translation>
    </message>
    <message>
      <location filename="package_list.py" line="211"/>
      <source>Click for details about workbench {}</source>
      <translation>Klicken für Details zum Arbeitsbereich {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="215"/>
      <source>Click for details about macro {}</source>
      <translation>Klicken für Details über Makro {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="326"/>
      <source>Maintainer</source>
      <translation>Maintainer</translation>
    </message>
    <message>
      <location filename="package_list.py" line="330"/>
      <source>Maintainers:</source>
      <translation>Maintainer:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="364"/>
      <source>Tags</source>
      <translation>Tags</translation>
    </message>
    <message>
      <location filename="package_list.py" line="371"/>
      <source>updated</source>
      <translation>aktualisiert</translation>
    </message>
    <message>
      <location filename="package_list.py" line="382"/>
      <source>Author</source>
      <translation>Autor</translation>
    </message>
    <message>
      <location filename="package_list.py" line="404"/>
      <source>Up-to-date</source>
      <translation>Auf dem neusten Stand</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="586"/>
      <source>Update available</source>
      <translation>Update verfügbar</translation>
    </message>
    <message>
      <location filename="package_list.py" line="414"/>
      <source>Pending restart</source>
      <translation>Ausstehender Neustart</translation>
    </message>
    <message>
      <location filename="package_list.py" line="498"/>
      <source>DISABLED</source>
      <translation>DEAKTIVIERT</translation>
    </message>
    <message>
      <location filename="package_list.py" line="372"/>
      <source>Installed version</source>
      <translation>Installierte Version</translation>
    </message>
    <message>
      <location filename="package_list.py" line="180"/>
      <source>Click for details about package</source>
      <translation>Für Details zum Paket klicken</translation>
    </message>
    <message>
      <location filename="package_list.py" line="185"/>
      <source>Click for details about workbench</source>
      <translation>Für Details zum Arbeitsbereich klicken</translation>
    </message>
    <message>
      <location filename="package_list.py" line="190"/>
      <source>Click for details about macro</source>
      <translation>Für Details zum Makro klicken</translation>
    </message>
    <message>
      <location filename="package_list.py" line="376"/>
      <source>Updated</source>
      <translation>Aktualisiert</translation>
    </message>
    <message>
      <location filename="package_list.py" line="380"/>
      <source>Unknown version</source>
      <translation>Unbekannte Version</translation>
    </message>
    <message>
      <location filename="package_list.py" line="383"/>
      <source>Installed on</source>
      <translation>Installiert am</translation>
    </message>
    <message>
      <location filename="package_list.py" line="394"/>
      <source>Available version</source>
      <translation>Verfügbare Version</translation>
    </message>
    <message>
      <location filename="package_list.py" line="566"/>
      <source>Show Addons containing:</source>
      <translation>Zeige Addons die folgendes enthalten:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="569"/>
      <source>All</source>
      <translation>Alles</translation>
    </message>
    <message>
      <location filename="package_list.py" line="572"/>
      <source>Workbenches</source>
      <translation>Arbeitsbereiche</translation>
    </message>
    <message>
      <location filename="package_list.py" line="575"/>
      <source>Macros</source>
      <translation>Makros</translation>
    </message>
    <message>
      <location filename="package_list.py" line="578"/>
      <source>Preference Packs</source>
      <translation>Einstellungs-Pakete</translation>
    </message>
    <message>
      <location filename="package_list.py" line="692"/>
      <source>Status:</source>
      <translation>Status:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="695"/>
      <source>Any</source>
      <translation>Alle</translation>
    </message>
    <message>
      <location filename="package_list.py" line="702"/>
      <source>Not installed</source>
      <translation>Nicht installiert</translation>
    </message>
    <message>
      <location filename="package_list.py" line="582"/>
      <source>Filter</source>
      <translation>Filter</translation>
    </message>
    <message>
      <location filename="package_list.py" line="585"/>
      <source>OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="115"/>
      <source>Checking network connection...
</source>
      <translation>Netzwerkverbindung wird überprüft...
</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="167"/>
      <source>Unable to download addon list.</source>
      <translation>Die Addon-Liste konnte nicht geladen werden.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="172"/>
      <source>Workbenches list was updated.</source>
      <translation>Die Liste der Arbeitsbereiche wurde aktualisiert.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="261"/>
      <source>Failed loading</source>
      <translation>Laden fehlgeschlagen</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="296"/>
      <source>List of macros successfully retrieved.</source>
      <translation>Die Makro-Liste wurde erfolgreich abgerufen.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="310"/>
      <source>GitPython not installed! Cannot retrieve macros from git</source>
      <translation>GitPython ist nicht installiert! Makros können nicht von Git abgerufen werden</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="319"/>
      <source>Something went wrong with the Git Macro Retrieval, possibly the Git executable is not in the path</source>
      <translation>Ein Fehler ist bei der Git-Makro Abfrage aufgetreten, möglicherweise befindet sich die ausführbare Git-Datei nicht in dem Pfad</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="343"/>
      <source>Appears to be an issue connecting to the Wiki, therefore cannot retrieve Wiki macro list at this time</source>
      <translation>Anscheinend ist ein Problem beim Verbinden mit dem Wiki aufgetreten, daher kann die Wiki-Makroliste zu diesem Zeitpunkt nicht abgerufen werden</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="367"/>
      <source>Unable to fetch git updates for workbench</source>
      <translation>Git-Updates für die Arbeitsbereiche können nicht abgerufen werden</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="391"/>
      <source>Retrieving info from</source>
      <translation>Lade informationen von</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="419"/>
      <source>Failed to read metadata from</source>
      <translation>Fehler beim Laden der Metadaten von</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="426"/>
      <source>git fetch failed for {}</source>
      <translation>Git-Fetch fehlgeschlagen für {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="429"/>
      <source>git fetch failed for {wb.name}</source>
      <translation>Git-Fetch fehlgeschlagen für {wb.name}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="433"/>
      <source>Raw markdown displayed</source>
      <translation>Unbearbeitetes Markdown angezeigt</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="435"/>
      <source>Python Markdown library is missing.</source>
      <translation>Python Markdown Bibliothek fehlt.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="439"/>
      <source>git pull failed for {wb.name}</source>
      <translation>git pull fehlgeschlagen für {wb.name}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="514"/>
      <source>Done locating macros.</source>
      <translation>Makro-Suche abgeschlossen.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="521"/>
      <source>This addon is already installed.</source>
      <translation>Dieses Addon ist bereits installiert.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="533"/>
      <source>An update is available for this addon.</source>
      <translation>Für dieses Addon ist ein Update verfügbar.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="547"/>
      <source>This addon is marked as obsolete</source>
      <translation>Dieses Addon ist als veraltet markiert</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="551"/>
      <source>This usually means it is no longer maintained, and some more advanced addon in this list provides the same functionality.</source>
      <translation>Dies bedeutet normalerweise, dass es nicht mehr gewartet wird und ein fortschrittlicheres Addon in dieser Liste die gleiche Funktionalität bietet.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="559"/>
      <source>This addon is marked as Python 2 Only</source>
      <translation>Dieses Addon ist als nur für Python 2 gekennzeichnet</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="564"/>
      <source>This workbench may no longer be maintained and installing it on a Python 3 system will more than likely result in errors at startup or while in use.</source>
      <translation>Dieser Arbeitsbereich wird möglicherweise nicht mehr gewartet und die Installation auf einem Python-3-System wird höchstwahrscheinlich zu Fehlern beim Start oder während der Nutzung führen.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="608"/>
      <source>An error occurred fetching macros from GitHub</source>
      <translation>Beim Abrufen von Makros von GitHub ist ein Fehler aufgetreten</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="646"/>
      <source>An error occurred updating macros from GitHub</source>
      <translation>Beim Aktualisieren der Makros von GitHub ist ein Fehler aufgetreten</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="651"/>
      <source>Retrieving description...</source>
      <translation>Beschreibung wird abgerufen...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="665"/>
      <source>This macro is already installed.</source>
      <translation>Dieses Makro ist bereits installiert.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="697"/>
      <source>Caching macro code...</source>
      <translation>Makro-Code wird zwischengespeichert...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="700"/>
      <source>GitPython not found. Using standard download instead.</source>
      <translation>GitPython wurde nicht gefunden. Stattdessen wird der Standarddownload verwendet.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="705"/>
      <source>Your version of python doesn&apos;t appear to support ZIP files. Unable to proceed.</source>
      <translation>Ihre Version von Python scheint ZIP-Dateien nicht zu unterstützen. Aktion kann nicht fortgesetzt werden.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="727"/>
      <source>User requested updating a Python 2 workbench on a system running Python 3 - </source>
      <translation>Der Benutzer hat die Aktualisierung eines Python-2-Arbeitsbereichs auf einem System mit Python 3 angefordert - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="738"/>
      <source>Outdated GitPython detected, consider upgrading with pip.</source>
      <translation>Es wurde eine veraltete GitPython-Version erkannt, erwäge das Upgrade mit Pip.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="763"/>
      <source>Workbench successfully updated. Please restart FreeCAD to apply the changes.</source>
      <translation>Arbeitsbereich erfolgreich aktualisiert.
Bitte FreeCAD neu starten, um die Änderungen zu übernehmen.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="771"/>
      <source>User requested installing a Python 2 workbench on a system running Python 3 - </source>
      <translation>Der Benutzer hat die Installation eines Python-2-Arbeitsbereichs auf einem System mit Python 3 angefordert - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="786"/>
      <source>Workbench successfully installed. Please restart FreeCAD to apply the changes.</source>
      <translation>Arbeitsbereich erfolgreich installiert. Bitte starten Sie FreeCAD neu, um die Änderungen anzuwenden.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="799"/>
      <source>A macro has been installed and is available under Macro -&gt; Macros menu</source>
      <translation>Ein Makro wurde installiert und ist verfügbar unter Makro -&gt; Makros-Menü</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="824"/>
      <source>Retrieving info from {}</source>
      <translation>Informationen von {} werden abgerufen</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="835"/>
      <source>Missing workbench</source>
      <translation>Fehlender Arbeitsbereich</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="844"/>
      <source>Missing python module</source>
      <translation>Fehlendes Python-Modul</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="854"/>
      <source>Missing optional python module (doesn&apos;t prevent installing)</source>
      <translation>Fehlendes optionales Python-Modul (verhindert nicht die Installation)</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="857"/>
      <source>Some errors were found that prevent to install this workbench</source>
      <translation>Einige Fehler verhindern die Installation dieses Arbeitsbereiches</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="859"/>
      <source>Please install the missing components first.</source>
      <translation>Bitte zuerst die fehlenden Komponenten installieren.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="873"/>
      <source>Error: Unable to locate zip from</source>
      <translation>Fehler: Zip-Datei kann nicht gefunden werden von</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="880"/>
      <source>Error: Unable to download</source>
      <translation>Fehler: Download nicht möglich</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="893"/>
      <source>Successfully installed</source>
      <translation>Installation erfolgreich</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="915"/>
      <source>Retrieving macro description...</source>
      <translation>Makro-Beschreibung wird abgerufen...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="653"/>
      <source>Retrieving info from git</source>
      <translation>Informationen werden von Git abgerufen</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="656"/>
      <source>Retrieving info from wiki</source>
      <translation>Informationen werden aus den Wiki abgerufen</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1013"/>
      <source>Error updating module</source>
      <translation>Fehler beim Aktualisieren des Moduls</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1075"/>
      <source>Error updating module </source>
      <translation>Fehler beim Aktualisieren des Moduls </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1078"/>
      <source>Please fix manually</source>
      <translation>Bitte manuell korrigieren</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1220"/>
      <source>Error: Unable to locate ZIP from</source>
      <translation>Fehler: Nicht gefunden ZIP-Datei von</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1403"/>
      <source>Retrieving package metadata...</source>
      <translation>Paket-Metadaten werden abgerufen...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1405"/>
      <source>Failed to execute pip. Returned error was:</source>
      <translation>Pip konnte nicht ausgeführt werden. Fehlermeldung war:</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1611"/>
      <source>Downloaded package.xml for {}</source>
      <translation>Package.xml heruntergeladen für {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1641"/>
      <source>Downloaded metadata.txt for {}</source>
      <translation>metadata.txt heruntergeladen für {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1715"/>
      <source>Downloaded icon for {}</source>
      <translation>Heruntergeladenes Icon für {}</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="332"/>
      <source>Failed to repair missing .git directory</source>
      <translation>Fehlendes .git-Verzeichnis konnte nicht repariert werden</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="335"/>
      <source>Repository URL</source>
      <translation>Repository-URL</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="338"/>
      <source>Clone directory</source>
      <translation>Verzeichnis klonen</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="72"/>
      <source>Error with encrypted connection</source>
      <translation>Fehler mit verschlüsselter Verbindung</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="135"/>
      <source>Failed to connect to</source>
      <translation>Keine Verbindung möglich mit</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="220"/>
      <source>Failed to connect to URL</source>
      <translation>Verbindung mit URL %@ nicht möglich</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="101"/>
      <source>DANGER: Developer feature</source>
      <translation>GEFAHR: Entwickler-Funktion</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="114"/>
      <source>There are local changes</source>
      <translation>Es gibt lokale Änderungen</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="192"/>
      <source>Branch</source>
      <comment>git terminology</comment>
      <translation>Git-Branch</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="178"/>
      <source>Tag</source>
      <comment>git terminology</comment>
      <translation>Markierung</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="261"/>
      <source>Kind</source>
      <comment>Table header for git ref type (e.g. either Tag or Branch)</comment>
      <translation>
        <numerusform>Art</numerusform>
        <numerusform>Arten</numerusform>
      </translation>
    </message>
    <message>
      <location filename="change_branch.py" line="265"/>
      <source>Local name</source>
      <comment>Table header for git ref name</comment>
      <translation>Lokaler Name</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="271"/>
      <source>Tracking</source>
      <comment>Table header for git remote tracking branch name name</comment>
      <translation type="unfinished">
        <numerusform>Nachverfolgen</numerusform>
        <numerusform>Tracking</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="277"/>
      <source>Local updated</source>
      <comment>Table header for git update time of local branch</comment>
      <translation type="unfinished">
        <numerusform>Lokale Version aktualisiert</numerusform>
        <numerusform>Local updated</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="283"/>
      <source>Remote updated</source>
      <comment>Table header for git update time of remote branch</comment>
      <translation type="unfinished">
        <numerusform>Entfernte Version aktualisiert</numerusform>
        <numerusform>Remote updated</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="191"/>
      <source>Checking connection</source>
      <translation>Verbindung wird überprüft</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="192"/>
      <source>Checking for connection to GitHub...</source>
      <translation>Verbindung zu GitHub wird überprüft...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="213"/>
      <source>Connection failed</source>
      <translation>Verbindung fehlgeschlagen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="240"/>
      <source>Missing dependency</source>
      <translation>Fehlende Abhängigkeit</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="324"/>
      <source>Starting up...</source>
      <translation>Wird gestartet...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="258"/>
      <source>Loading addon information</source>
      <translation>Lade Addon-Informationen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="199"/>
      <source>Addon manager</source>
      <translation>Addon-Manager</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="209"/>
      <source>Restart now</source>
      <translation>Jetzt neu starten</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="210"/>
      <source>Restart later</source>
      <translation>Später neu starten</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1248"/>
      <source>Refresh local cache</source>
      <translation>Lokalen Cache aktualisieren</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="659"/>
      <source>Updating cache...</source>
      <translation>Cache wird aktualisiert...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="766"/>
      <source>Could not find addon &apos;{}&apos; to select
</source>
      <translation>Add-on &apos; konnte nicht gefunden werden, {}&apos; um auszuwählen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="243"/>
      <source>Checking for updates...</source>
      <translation>Nach Updates suchen...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="773"/>
      <source>Apply {} update(s)</source>
      <translation>{} Update(s) anwenden</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="577"/>
      <source>No updates available</source>
      <translation>Keine Aktualisierungen verfügbar</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="915"/>
      <source>Too many to list</source>
      <translation>Zu viele zum Auflisten</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="893"/>
      <source>Missing Requirement</source>
      <translation>Fehlende Voraussetzung</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="86"/>
      <source>The addons that can be installed here are not officially part of FreeCAD, and are not reviewed by the FreeCAD team. Make sure you know what you are installing!</source>
      <translation>Die Addons, die hier installiert werden können, sind nicht offiziell Teil von FreeCAD und werden nicht vom FreeCAD Team überprüft. Stellen Sie sicher, dass Sie wissen, was Sie installieren!</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="203"/>
      <source>You must restart FreeCAD for changes to take effect.</source>
      <translation>FreeCAD muss neu gestartet werden, damit die Änderungen wirksam werden.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="204"/>
      <source>You must restart FreeCAD for changes to take effect. Press Ok to restart FreeCAD now, or Cancel to restart later.</source>
      <translation>FreeCAD muss neu gestartet werden, damit die Änderungen wirksam werden. Ok drücken, um FreeCAD jetzt neu zu starten oder Abbrechen, um später neu zu starten.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="241"/>
      <source>Could not import QtNetwork -- see Report View for details. Addon Manager unavailable.</source>
      <translation>QtNetwork konnte nicht importiert werden - siehe Berichtsansicht für Details. Der Addon Manager ist nicht verfügbar.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="262"/>
      <source>Apply</source>
      <translation>Übernehmen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="263"/>
      <source>update(s)</source>
      <translation>Update(s)</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="266"/>
      <source>No update available</source>
      <translation>Kein Update verfügbar</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="433"/>
      <source>Macro successfully installed. The macro is now available from the Macros dialog.</source>
      <translation>Das Makro wurde erfolgreich installiert. Es ist nun im Macros-Dialog verfügbar.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="435"/>
      <source>Unable to install</source>
      <translation>Installation nicht möglich</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="494"/>
      <source>Addon successfully removed. Please restart FreeCAD</source>
      <translation>Das Addon wurde erfolgreich entfernt. Bitte FreeCAD neu starten</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="496"/>
      <source>Unable to remove this addon</source>
      <translation>Dieses Addon konnte nicht entfernt werden</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="502"/>
      <source>Macro successfully removed.</source>
      <translation>Das Makro wurde erfolgreich entfernt.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="504"/>
      <source>Macro could not be removed.</source>
      <translation>Das Makro konnte nicht entfernt werden.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="534"/>
      <source>Addon Manager: Skipping update check because AutoCheck user preference is False</source>
      <translation>Addon-Manager: Überspringen der Aktualisierungsprüfung, weil die Benutzereinstellung "AutoCheck" auf "false" gesetzt ist</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="542"/>
      <source>Restart required</source>
      <translation>Neustart erforderlich</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="774"/>
      <source>All packages updates failed. Packages:</source>
      <translation>Alle Paketaktualisierungen sind fehlgeschlagen. Pakete:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="786"/>
      <source>Failed packages:</source>
      <translation>Fehlgeschlagene Pakete:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1079"/>
      <source>Press OK to install anyway.</source>
      <translation>OK drücken, um trotzdem zu installieren.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="964"/>
      <source>Installing dependencies</source>
      <translation>Abhängigkeiten werden installiert</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1061"/>
      <source>Cannot execute Python</source>
      <translation>Python kann nicht ausgeführt werden</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1081"/>
      <source>Cannot execute pip</source>
      <translation>Pip kann nicht ausgeführt werden</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1102"/>
      <source>Package installation failed</source>
      <translation>Paketinstallation fehlgeschlagen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1105"/>
      <source>See Report View for detailed failure log.</source>
      <translation>Detaillierte Fehlerprotokolle finden Sie in der Report-Ansicht.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="703"/>
      <source>Installation of macro failed</source>
      <translation>Installation des Makros fehlgeschlagen</translation>
    </message>
    <message numerus="yes">
      <location filename="AddonManager.py" line="1280"/>
      <source>{} total, see Report view for list</source>
      <comment>Describes the number of updates that were completed (&apos;{}&apos; is replaced by the number of updates)</comment>
      <translation>
        <numerusform>{} insgesamt, siehe Report-Ansicht für die Liste</numerusform>
        <numerusform>{} insgesamt, siehe Report-Ansicht für die Liste</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1178"/>
      <source>Succeeded</source>
      <translation>Erfolgreich</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1159"/>
      <source>All packages updates failed:</source>
      <translation>Alle Paketaktualisierungen sind fehlgeschlagen:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1183"/>
      <source>Failed</source>
      <translation>Fehlgeschlagen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="800"/>
      <source>Update report</source>
      <translation>Bericht aktualisieren</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="850"/>
      <source>Installation succeeded</source>
      <translation>Installation erfolgreich</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="866"/>
      <source>Installation failed</source>
      <translation>Installation fehlgeschlagen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1457"/>
      <source>Confirm remove</source>
      <translation>Entfernen bestätigen</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1460"/>
      <source>Are you sure you want to uninstall this Addon?</source>
      <translation>Soll dieses Addon wirklich deinstalliert werden?</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1513"/>
      <source>Execution of Addon&apos;s uninstall.py script failed. Proceeding with uninstall...</source>
      <translation>Ausführung des Addon&apos;s Uninstall.py Skripts fehlgeschlagen. Fortfahren mit der Deinstallation...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1558"/>
      <source>Successfully uninstalled {}</source>
      <translation>{} erfolgreich deinstalliert</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="157"/>
      <source>Unable to fetch the code of this macro.</source>
      <translation>Der Code dieses Makros kann nicht abgerufen werden.</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="164"/>
      <source>Unable to retrieve a description for this macro.</source>
      <translation>Eine Beschreibung für dieses Makro kann nicht abgerufen werden.</translation>
    </message>
  </context>
  <context>
    <name>Std_AddonMgr</name>
    <message>
      <location filename="AddonManager.py" line="68"/>
      <source>&amp;Addon manager</source>
      <translation>&amp;Addon-Manager</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="69"/>
      <source>Manage external workbenches and macros</source>
      <translation>Externe Arbeitsbereiche und Makros verwalten</translation>
    </message>
  </context>
  <context>
    <name>AddonInstaller</name>
    <message>
      <location filename="addonmanager_workers.py" line="535"/>
      <source>Installed location</source>
      <translation>Installationsort</translation>
    </message>
  </context>
  <context>
    <name>Dialog</name>
    <message>
      <location filename="../../AddonManager.ui" line="14"/>
      <source>Addon Manager</source>
      <translation>Addon-Manager</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="37"/>
      <source>Workbenches</source>
      <translation>Arbeitsbereiche</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="47"/>
      <source>Macros</source>
      <translation>Makros</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="56"/>
      <source>Executes the selected macro, if installed</source>
      <translation>Führt das ausgewählte Makro aus, sofern installiert</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="59"/>
      <source>Execute</source>
      <translation>Ausführen</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="89"/>
      <source>Sets configuration options for the Addon Manager</source>
      <translation>Setzt Konfigurationsoptionen für den Addon-Manager</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="92"/>
      <source>Configure...</source>
      <translation>Konfigurieren...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="113"/>
      <source>Downloading info...</source>
      <translation>Info wird heruntergeladen...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="127"/>
      <source>Uninstalls a selected macro or workbench</source>
      <translation>Deinstalliert ein ausgewähltes Makro oder einen Arbeitsbereich</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="130"/>
      <source>Uninstall selected</source>
      <translation>Ausgewählte deinstallieren</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="137"/>
      <source>Installs or updates the selected macro or workbench</source>
      <translation>Installiert oder aktualisiert das ausgewählte Makro oder den gewählten Arbeitsbereich</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="140"/>
      <source>Install/update selected</source>
      <translation>Ausgewählte installieren/aktualisieren</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="147"/>
      <source>Download and apply all available updates</source>
      <translation>Alle verfügbaren Updates herunterladen und anwenden</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="150"/>
      <source>Update all</source>
      <translation>Alle aktualisieren</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="157"/>
      <source>Close the Addon Manager</source>
      <translation>Addon-Manager schließen</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="160"/>
      <source>Close</source>
      <translation>Schließen</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="14"/>
      <source>Addon manager options</source>
      <translation>Addon-Manager-Optionen</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="20"/>
      <source>If this option is selected, when launching the Addon Manager,
installed addons will be checked for available updates
(this requires the GitPython package installed on your system)</source>
      <translation>Wenn beim Starten des Addon-Managers diese Option ausgewählt ist,
werden die installierten Addons auf verfügbare Updates überprüft.
(Dazu muss das GitPython Paket auf dem System installiert sein)</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="25"/>
      <source>Automatically check for updates at start (requires GitPython)</source>
      <translation>Automatisch beim Start nach Updates suchen (benötigt GitPython)</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="35"/>
      <source>Custom repositories (one per line):</source>
      <translation>Eigene Ablageordner (einer pro Zeile):</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="42"/>
      <source>You can use this window to specify additional addon repositories
to be scanned for available addons</source>
      <translation>Dieses Fenster kann verwendet werden, um zusätzliche Addon-Ablageordner auszuwählen, die nach verfügbaren Addons durchsucht werden</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="57"/>
      <source>Proxy </source>
      <translation>Proxy </translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="64"/>
      <source>No proxy</source>
      <translation>Kein Proxy</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="71"/>
      <source>User system proxy</source>
      <translation>Benutzer-System-Proxy</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="78"/>
      <source>User defined proxy :</source>
      <translation>Benutzerdefinierter Proxy:</translation>
    </message>
  </context>
</TS>
