<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="fr" sourcelanguage="en">
  <context>
    <name>AddonsInstaller</name>
    <message>
      <location filename="install_to_toolbar.py" line="76"/>
      <source>Create new toolbar</source>
      <translation type="unfinished">Create new toolbar</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="219"/>
      <source>A macro installed with the FreeCAD Addon Manager</source>
      <translation type="unfinished">A macro installed with the FreeCAD Addon Manager</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="221"/>
      <source>Run</source>
      <comment>Indicates a macro that can be &apos;run&apos;</comment>
      <translation>Exécuter</translation>
    </message>
    <message>
      <location filename="package_details.py" line="112"/>
      <source>Version {version} installed on {date}</source>
      <translation>Version {version} installée le {date}</translation>
    </message>
    <message>
      <location filename="package_details.py" line="117"/>
      <source>Version {version} installed</source>
      <translation>Version installée {version}</translation>
    </message>
    <message>
      <location filename="package_details.py" line="121"/>
      <source>Installed on {date}</source>
      <translation>Installé le {date}</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="567"/>
      <source>Installed</source>
      <translation>Installé</translation>
    </message>
    <message>
      <location filename="package_details.py" line="96"/>
      <source>Version</source>
      <translation>Version</translation>
    </message>
    <message>
      <location filename="package_details.py" line="103"/>
      <source>Unknown version (no package.xml file found)</source>
      <translation>Version inconnue (aucun fichier package.xml trouvé)</translation>
    </message>
    <message>
      <location filename="package_details.py" line="108"/>
      <source>installed on</source>
      <translation>installé le</translation>
    </message>
    <message>
      <location filename="package_details.py" line="118"/>
      <source>installed</source>
      <translation>installé</translation>
    </message>
    <message>
      <location filename="package_details.py" line="126"/>
      <source>Update available to version</source>
      <translation>Mise à jour disponible pour la version</translation>
    </message>
    <message>
      <location filename="package_details.py" line="144"/>
      <source>This is the latest version available</source>
      <translation>Ceci est la dernière version disponible</translation>
    </message>
    <message>
      <location filename="package_details.py" line="151"/>
      <source>Updated, please restart FreeCAD to use</source>
      <translation>Mis à jour, veuillez redémarrer FreeCAD pour l’utiliser</translation>
    </message>
    <message>
      <location filename="package_details.py" line="159"/>
      <source>Update check in progress</source>
      <translation>Recherche de mise à jour en cours</translation>
    </message>
    <message>
      <location filename="package_details.py" line="163"/>
      <source>Automatic update checks disabled</source>
      <translation>Recherche automatique de mises à jour désactivée</translation>
    </message>
    <message>
      <location filename="package_details.py" line="172"/>
      <source>Installation location</source>
      <translation>Emplacement d’installation</translation>
    </message>
    <message>
      <location filename="package_details.py" line="240"/>
      <source>WARNING: This addon is obsolete</source>
      <translation>AVERTISSEMENT : Ce module est obsolète</translation>
    </message>
    <message>
      <location filename="package_details.py" line="250"/>
      <source>WARNING: This addon is Python 2 Only</source>
      <translation>AVERTISSEMENT : Ce module utilise Python 2 seulement</translation>
    </message>
    <message>
      <location filename="package_details.py" line="312"/>
      <source>Fetching README.md from package repository</source>
      <translation>Récupération de README.md depuis le dépôt des paquets</translation>
    </message>
    <message>
      <location filename="package_details.py" line="354"/>
      <source>WARNING: This addon requires FreeCAD </source>
      <translation>AVERTISSEMENT : cette extension nécessite FreeCAD </translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="431"/>
      <source>Delete cached version of this README and re-download</source>
      <translation>
        <numerusform>Supprimer la version mise en cache de ce README et -télécharger de nouveau</numerusform>
        <numerusform>Supprimer la version mise en cache de ce README et télécharger de nouveau</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_details.py" line="563"/>
      <source>Could not load README data from URL {}</source>
      <translation>Impossible de charger les données README depuis l'URL {}</translation>
    </message>
    <message>
      <location filename="package_details.py" line="577"/>
      <source>Success</source>
      <translation>Succès</translation>
    </message>
    <message>
      <location filename="package_details.py" line="600"/>
      <source>Changed to git ref &apos;{}&apos; -- please restart to use Addon.</source>
      <translation>Changé pour git ref &apos;{}&apos; -- Merci de redémarrer pour utiliser le greffon.</translation>
    </message>
    <message>
      <location filename="package_details.py" line="636"/>
      <source>Page JavaScript reported</source>
      <translation>JavaScript de la page signalé</translation>
    </message>
    <message>
      <location filename="package_details.py" line="407"/>
      <source>Install</source>
      <translation>Installer</translation>
    </message>
    <message>
      <location filename="package_details.py" line="410"/>
      <source>Uninstall</source>
      <translation>Désinstaller</translation>
    </message>
    <message>
      <location filename="package_details.py" line="413"/>
      <source>Update</source>
      <translation>Mettre à jour</translation>
    </message>
    <message>
      <location filename="package_details.py" line="416"/>
      <source>Check for Update</source>
      <translation>Rechercher des mises à jour</translation>
    </message>
    <message>
      <location filename="package_details.py" line="419"/>
      <source>Run Macro</source>
      <translation>Exécuter la Macro</translation>
    </message>
    <message>
      <location filename="package_details.py" line="786"/>
      <source>Change Branch</source>
      <translation>Changer de branche</translation>
    </message>
    <message>
      <location filename="package_details.py" line="867"/>
      <source>Enable</source>
      <translation>Activer</translation>
    </message>
    <message>
      <location filename="package_details.py" line="870"/>
      <source>Disable</source>
      <translation>Désactiver</translation>
    </message>
    <message>
      <location filename="package_details.py" line="424"/>
      <source>Return to package list</source>
      <translation>Retourner à la liste des paquets</translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="800"/>
      <source>QtWebEngine Python bindings not installed -- using fallback README display. See Report View for details and installation instructions.</source>
      <translation>
        <numerusform>Les bindings Python de QtWebEngine ne sont pas installés -- utilisation de l'affichage README de repli. Consultez la vue de rapport pour plus de détails et les instructions d'installation.</numerusform>
        <numerusform>Les bindings Python de QtWebEngine ne sont pas installés -- en utilisant l'affichage README de repli. Consultez la vue de rapport pour plus de détails et les instructions d'installation.</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_list.py" line="119"/>
      <source>Filter is valid</source>
      <translation>Le filtre est valide</translation>
    </message>
    <message>
      <location filename="package_list.py" line="125"/>
      <source>Filter regular expression is invalid</source>
      <translation>L’expression rationnelle du filtre n’est pas valable</translation>
    </message>
    <message>
      <location filename="package_list.py" line="207"/>
      <source>Click for details about package {}</source>
      <translation>Cliquer pour plus de détails sur le paquet {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="211"/>
      <source>Click for details about workbench {}</source>
      <translation>Cliquer pour plus de détails sur l'atelier {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="215"/>
      <source>Click for details about macro {}</source>
      <translation>Cliquer pour plus de détails sur la macro {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="326"/>
      <source>Maintainer</source>
      <translation>Mainteneur</translation>
    </message>
    <message>
      <location filename="package_list.py" line="330"/>
      <source>Maintainers:</source>
      <translation>Mainteneurs :</translation>
    </message>
    <message>
      <location filename="package_list.py" line="364"/>
      <source>Tags</source>
      <translation>Mots-Clés</translation>
    </message>
    <message>
      <location filename="package_list.py" line="371"/>
      <source>updated</source>
      <translation>Mis à jour</translation>
    </message>
    <message>
      <location filename="package_list.py" line="382"/>
      <source>Author</source>
      <translation>Auteur</translation>
    </message>
    <message>
      <location filename="package_list.py" line="404"/>
      <source>Up-to-date</source>
      <translation>À jour</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="586"/>
      <source>Update available</source>
      <translation>Mise à jour disponible</translation>
    </message>
    <message>
      <location filename="package_list.py" line="414"/>
      <source>Pending restart</source>
      <translation>En attente de redémarrage</translation>
    </message>
    <message>
      <location filename="package_list.py" line="498"/>
      <source>DISABLED</source>
      <translation type="unfinished">DISABLED</translation>
    </message>
    <message>
      <location filename="package_list.py" line="372"/>
      <source>Installed version</source>
      <translation>Version installée</translation>
    </message>
    <message>
      <location filename="package_list.py" line="180"/>
      <source>Click for details about package</source>
      <translation>Cliquer pour plus de détails sur le paquet</translation>
    </message>
    <message>
      <location filename="package_list.py" line="185"/>
      <source>Click for details about workbench</source>
      <translation>Cliquer pour plus de détails sur l'atelier</translation>
    </message>
    <message>
      <location filename="package_list.py" line="190"/>
      <source>Click for details about macro</source>
      <translation>Cliquer pour plus de détails sur la macro</translation>
    </message>
    <message>
      <location filename="package_list.py" line="376"/>
      <source>Updated</source>
      <translation>Mis à jour</translation>
    </message>
    <message>
      <location filename="package_list.py" line="380"/>
      <source>Unknown version</source>
      <translation>Version inconnue</translation>
    </message>
    <message>
      <location filename="package_list.py" line="383"/>
      <source>Installed on</source>
      <translation>Installée le</translation>
    </message>
    <message>
      <location filename="package_list.py" line="394"/>
      <source>Available version</source>
      <translation>Version disponible</translation>
    </message>
    <message>
      <location filename="package_list.py" line="566"/>
      <source>Show Addons containing:</source>
      <translation>Afficher les greffons contenant :</translation>
    </message>
    <message>
      <location filename="package_list.py" line="569"/>
      <source>All</source>
      <translation>Tous</translation>
    </message>
    <message>
      <location filename="package_list.py" line="572"/>
      <source>Workbenches</source>
      <translation>Ateliers</translation>
    </message>
    <message>
      <location filename="package_list.py" line="575"/>
      <source>Macros</source>
      <translation>Macros</translation>
    </message>
    <message>
      <location filename="package_list.py" line="578"/>
      <source>Preference Packs</source>
      <translation>Kits de préférences</translation>
    </message>
    <message>
      <location filename="package_list.py" line="692"/>
      <source>Status:</source>
      <translation>État:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="695"/>
      <source>Any</source>
      <translation>Quelconque</translation>
    </message>
    <message>
      <location filename="package_list.py" line="702"/>
      <source>Not installed</source>
      <translation>Non installé</translation>
    </message>
    <message>
      <location filename="package_list.py" line="582"/>
      <source>Filter</source>
      <translation>Filtre</translation>
    </message>
    <message>
      <location filename="package_list.py" line="585"/>
      <source>OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="115"/>
      <source>Checking network connection...
</source>
      <translation>Vérification de la connexion au réseau...
</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="167"/>
      <source>Unable to download addon list.</source>
      <translation>Impossible de télécharger la liste des greffons.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="172"/>
      <source>Workbenches list was updated.</source>
      <translation>La liste des ateliers a été mise à jour.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="261"/>
      <source>Failed loading</source>
      <translation>Échec du chargement</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="296"/>
      <source>List of macros successfully retrieved.</source>
      <translation>Liste des macros récupérée avec succès.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="310"/>
      <source>GitPython not installed! Cannot retrieve macros from git</source>
      <translation>GitPython n'est pas installé. Impossible de récupérer les macros depuis git</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="319"/>
      <source>Something went wrong with the Git Macro Retrieval, possibly the Git executable is not in the path</source>
      <translation>Une erreur s'est produite lors de la Récupération de Macro Git, peut-être que l'exécutable Git n'est pas dans le chemin d'accès</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="343"/>
      <source>Appears to be an issue connecting to the Wiki, therefore cannot retrieve Wiki macro list at this time</source>
      <translation>Il semble y avoir un problème de connexion au Wiki, la liste des macros du Wiki ne peut donc pas être récupérée pour le moment</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="367"/>
      <source>Unable to fetch git updates for workbench</source>
      <translation>Impossible de récupérer les mises à jour git pour l'atelier</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="391"/>
      <source>Retrieving info from</source>
      <translation>Récupération des informations de</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="419"/>
      <source>Failed to read metadata from</source>
      <translation>Impossible de lire les métadonnées depuis</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="426"/>
      <source>git fetch failed for {}</source>
      <translation>La récupération de git a échoué pour {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="429"/>
      <source>git fetch failed for {wb.name}</source>
      <translation>La récupération de git a échoué pour {wb.name}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="433"/>
      <source>Raw markdown displayed</source>
      <translation>Affichage du Markdown brut</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="435"/>
      <source>Python Markdown library is missing.</source>
      <translation>La bibliothèque Python Markdown est manquante.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="439"/>
      <source>git pull failed for {wb.name}</source>
      <translation>git pull a échoué pour {wb.name}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="514"/>
      <source>Done locating macros.</source>
      <translation>La localisation des macros est terminée.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="521"/>
      <source>This addon is already installed.</source>
      <translation>Ce greffon est déjà installé.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="533"/>
      <source>An update is available for this addon.</source>
      <translation>Une mise à jour est disponible pour ce greffon.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="547"/>
      <source>This addon is marked as obsolete</source>
      <translation>Ce greffon est marqué comme obsolète</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="551"/>
      <source>This usually means it is no longer maintained, and some more advanced addon in this list provides the same functionality.</source>
      <translation>Cela signifie généralement qu'il n'est plus maintenu, et que d'autres greffons plus perfectionnés proposant les mêmes fonctionnalités sont disponibles.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="559"/>
      <source>This addon is marked as Python 2 Only</source>
      <translation>Cet addon est indiqué pour Python 2 uniquement</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="564"/>
      <source>This workbench may no longer be maintained and installing it on a Python 3 system will more than likely result in errors at startup or while in use.</source>
      <translation>Cet atelier peut ne plus être maintenu et l'installer sur un système Python 3 entraînera très probablement des erreurs au démarrage ou en cours d'utilisation.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="608"/>
      <source>An error occurred fetching macros from GitHub</source>
      <translation>Une erreur est survenue lors de la récupération des macros depuis GitHub</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="646"/>
      <source>An error occurred updating macros from GitHub</source>
      <translation type="unfinished">An error occurred updating macros from GitHub</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="651"/>
      <source>Retrieving description...</source>
      <translation>Récupération de la description...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="665"/>
      <source>This macro is already installed.</source>
      <translation>Cette macro est déjà installée.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="697"/>
      <source>Caching macro code...</source>
      <translation>Mise en cache du code de la macro...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="700"/>
      <source>GitPython not found. Using standard download instead.</source>
      <translation>GitPython est introuvable. Utilisation du téléchargement standard.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="705"/>
      <source>Your version of python doesn&apos;t appear to support ZIP files. Unable to proceed.</source>
      <translation>Votre version de Python semble ne pas supporter les fichiers ZIP. Impossible de continuer.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="727"/>
      <source>User requested updating a Python 2 workbench on a system running Python 3 - </source>
      <translation>L'utilisateur a demandé la mise à jour d'un atelier Python 2 sur un système Python 3 - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="738"/>
      <source>Outdated GitPython detected, consider upgrading with pip.</source>
      <translation>La version de GitPython est obsolète, envisagez de mettre à jour avec pip.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="763"/>
      <source>Workbench successfully updated. Please restart FreeCAD to apply the changes.</source>
      <translation>Atelier mis à jour avec succès. Veuillez redémarrer FreeCAD pour appliquer les modifications.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="771"/>
      <source>User requested installing a Python 2 workbench on a system running Python 3 - </source>
      <translation>L'utilisateur a demandé l'installation d'un atelier Python 2 sur un système exécutant Python 3 - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="786"/>
      <source>Workbench successfully installed. Please restart FreeCAD to apply the changes.</source>
      <translation>Atelier installé avec succès. Veuillez redémarrer FreeCAD pour appliquer les modifications.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="799"/>
      <source>A macro has been installed and is available under Macro -&gt; Macros menu</source>
      <translation>Une macro a été installée et est disponible dans le menu Macro -&gt; Macros</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="824"/>
      <source>Retrieving info from {}</source>
      <translation>Récupération des informations de {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="835"/>
      <source>Missing workbench</source>
      <translation>Atelier manquant</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="844"/>
      <source>Missing python module</source>
      <translation>Module Python manquant</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="854"/>
      <source>Missing optional python module (doesn&apos;t prevent installing)</source>
      <translation>Un module Python optionnel est manquant (mais n'empêche pas l'installation)</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="857"/>
      <source>Some errors were found that prevent to install this workbench</source>
      <translation>Des erreurs sont survenues et empêchent l'installation de cet atelier</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="859"/>
      <source>Please install the missing components first.</source>
      <translation>Veuillez d'abord installer les composants manquants.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="915"/>
      <source>Retrieving macro description...</source>
      <translation>Récupération de la description de la macro...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="653"/>
      <source>Retrieving info from git</source>
      <translation>Récupération des informations depuis git</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="873"/>
      <source>Error: Unable to locate zip from</source>
      <translation>Erreur: Impossible de localiser le zip de</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="656"/>
      <source>Retrieving info from wiki</source>
      <translation>Récupération des informations depuis le wiki</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="880"/>
      <source>Error: Unable to download</source>
      <translation>Erreur : impossible de télécharger</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="893"/>
      <source>Successfully installed</source>
      <translation>Installation réussie</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1013"/>
      <source>Error updating module</source>
      <translation type="unfinished">Error updating module</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1078"/>
      <source>Please fix manually</source>
      <translation>Veuillez corriger manuellement</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1075"/>
      <source>Error updating module </source>
      <translation>Erreur lors de la mise à jour du module </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1220"/>
      <source>Error: Unable to locate ZIP from</source>
      <translation>Erreur: Impossible de localiser le ZIP depuis</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1403"/>
      <source>Retrieving package metadata...</source>
      <translation>Récupération des métadonnées du paquet...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1405"/>
      <source>Failed to execute pip. Returned error was:</source>
      <translation>Impossible d'exécuter pip. L'erreur retournée était :</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1611"/>
      <source>Downloaded package.xml for {}</source>
      <translation>Package.xml téléchargé pour {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1641"/>
      <source>Downloaded metadata.txt for {}</source>
      <translation>Metadata.txt téléchargée pour {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1715"/>
      <source>Downloaded icon for {}</source>
      <translation>Icône téléchargée pour {}</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="332"/>
      <source>Failed to repair missing .git directory</source>
      <translation>Impossible de réparer le répertoire .git manquant</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="335"/>
      <source>Repository URL</source>
      <translation>URL du dépôt</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="338"/>
      <source>Clone directory</source>
      <translation>Cloner le répertoire</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="72"/>
      <source>Error with encrypted connection</source>
      <translation>Erreur avec la connexion chiffrée</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="135"/>
      <source>Failed to connect to</source>
      <translation>Échec de connexion à</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="220"/>
      <source>Failed to connect to URL</source>
      <translation>Échec de la connexion à l'URL</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="101"/>
      <source>DANGER: Developer feature</source>
      <translation>DANGER : fonctionnalité développeur</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="114"/>
      <source>There are local changes</source>
      <translation>Il y a des changements locaux</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="192"/>
      <source>Branch</source>
      <comment>git terminology</comment>
      <translation>Branche</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="178"/>
      <source>Tag</source>
      <comment>git terminology</comment>
      <translation>Étiquette</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="261"/>
      <source>Kind</source>
      <comment>Table header for git ref type (e.g. either Tag or Branch)</comment>
      <translation>
        <numerusform>Type</numerusform>
        <numerusform>Type</numerusform>
      </translation>
    </message>
    <message>
      <location filename="change_branch.py" line="265"/>
      <source>Local name</source>
      <comment>Table header for git ref name</comment>
      <translation>Nom local</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="271"/>
      <source>Tracking</source>
      <comment>Table header for git remote tracking branch name name</comment>
      <translation>
        <numerusform>Traçage</numerusform>
        <numerusform>Traçage</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="277"/>
      <source>Local updated</source>
      <comment>Table header for git update time of local branch</comment>
      <translation>
        <numerusform>Mise à jour locale</numerusform>
        <numerusform>Mise à jour locale</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="283"/>
      <source>Remote updated</source>
      <comment>Table header for git update time of remote branch</comment>
      <translation type="unfinished">
        <numerusform>Mis à jour à distance</numerusform>
        <numerusform>Remote updated</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="191"/>
      <source>Checking connection</source>
      <translation>Vérification de la connexion</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="192"/>
      <source>Checking for connection to GitHub...</source>
      <translation>Recherche de connexion à GitHub...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="213"/>
      <source>Connection failed</source>
      <translation>La connexion a échoué</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="240"/>
      <source>Missing dependency</source>
      <translation>Dépendances manquantes</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="324"/>
      <source>Starting up...</source>
      <translation>Démarrage en cours...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="258"/>
      <source>Loading addon information</source>
      <translation>Chargement des informations du greffon</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="199"/>
      <source>Addon manager</source>
      <translation>Gestionnaire d'Addons</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="209"/>
      <source>Restart now</source>
      <translation>Redémarrer maintenant</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="210"/>
      <source>Restart later</source>
      <translation>Redémarrer plus tard</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1248"/>
      <source>Refresh local cache</source>
      <translation>Rafraîchir le cache local</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="659"/>
      <source>Updating cache...</source>
      <translation>Mise à jour du cache...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="243"/>
      <source>Checking for updates...</source>
      <translation>Recherche de mises à jour...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="773"/>
      <source>Apply {} update(s)</source>
      <translation>Appliquer {} mise(s) à jour</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="86"/>
      <source>The addons that can be installed here are not officially part of FreeCAD, and are not reviewed by the FreeCAD team. Make sure you know what you are installing!</source>
      <translation>Les extensions qui peuvent être installées ici ne font pas partie de FreeCAD, et ne sont pas officiellement approuvées par l'équipe de FreeCAD. Assurez-vous de savoir ce que vous installez !</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="203"/>
      <source>You must restart FreeCAD for changes to take effect.</source>
      <translation>Vous devez redémarrer FreeCAD pour que les changements prennent effet.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="204"/>
      <source>You must restart FreeCAD for changes to take effect. Press Ok to restart FreeCAD now, or Cancel to restart later.</source>
      <translation>Vous devez redémarrer FreeCAD pour que les changements prennent effet. Appuyez sur Ok pour redémarrer FreeCAD maintenant, ou Annuler pour redémarrer plus tard.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="241"/>
      <source>Could not import QtNetwork -- see Report View for details. Addon Manager unavailable.</source>
      <translation>Impossible d'importer QtNetwork -- Voir la vue rapport pour plus de détails. Addon Manager indisponible.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="262"/>
      <source>Apply</source>
      <translation>Appliquer</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="263"/>
      <source>update(s)</source>
      <translation>mise(s) à jour</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="266"/>
      <source>No update available</source>
      <translation>Aucune mise à jour disponible</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="433"/>
      <source>Macro successfully installed. The macro is now available from the Macros dialog.</source>
      <translation>Macro installée avec succès. Elle est maintenant disponible dans le menu Macro.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="435"/>
      <source>Unable to install</source>
      <translation>Impossible d'installer</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="494"/>
      <source>Addon successfully removed. Please restart FreeCAD</source>
      <translation>Addon installé avec succès. Veuillez redémarrer FreeCAD</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="496"/>
      <source>Unable to remove this addon</source>
      <translation>Impossible de désinstaller ce greffon</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="502"/>
      <source>Macro successfully removed.</source>
      <translation>Macro désinstallée avec succès.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="504"/>
      <source>Macro could not be removed.</source>
      <translation>La macro n'a pas pu être désinstallée.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="534"/>
      <source>Addon Manager: Skipping update check because AutoCheck user preference is False</source>
      <translation>Gestionnaire d'extensions : Ignorer la vérification de mise à jour parce que la préférence de l'utilisateur est Fausse</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="542"/>
      <source>Restart required</source>
      <translation>Redémarrage requis</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="577"/>
      <source>No updates available</source>
      <translation>Aucune mise à jour disponible</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="774"/>
      <source>All packages updates failed. Packages:</source>
      <translation>La mise à jour de tous les paquets a échoué. Paquets :</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="786"/>
      <source>Failed packages:</source>
      <translation>Paquets échoués:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="915"/>
      <source>Too many to list</source>
      <translation>Trop de valeurs à afficher</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="893"/>
      <source>Missing Requirement</source>
      <translation>Élément Manquant</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="964"/>
      <source>Installing dependencies</source>
      <translation>Installation des dépendances</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1061"/>
      <source>Cannot execute Python</source>
      <translation>Impossible d'exécuter Python</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1081"/>
      <source>Cannot execute pip</source>
      <translation>Impossible d'exécuter pip</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1102"/>
      <source>Package installation failed</source>
      <translation>L'installation du paquet a échoué</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1105"/>
      <source>See Report View for detailed failure log.</source>
      <translation>Reportez-vous à la vue rapport pour plus de détails sur les échecs.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="703"/>
      <source>Installation of macro failed</source>
      <translation>L'installation de la macro a échoué</translation>
    </message>
    <message numerus="yes">
      <location filename="AddonManager.py" line="1280"/>
      <source>{} total, see Report view for list</source>
      <comment>Describes the number of updates that were completed (&apos;{}&apos; is replaced by the number of updates)</comment>
      <translation>
        <numerusform>{} au total, voir la vue Rapport pour la liste</numerusform>
        <numerusform>{} au total, voir la vue Rapport pour la liste</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1178"/>
      <source>Succeeded</source>
      <translation>Réussi</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1159"/>
      <source>All packages updates failed:</source>
      <translation>Toutes les mises à jour de paquets ont échoué:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1183"/>
      <source>Failed</source>
      <translation>Échoué</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="800"/>
      <source>Update report</source>
      <translation>Mise à jour des dépots</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="850"/>
      <source>Installation succeeded</source>
      <translation>Installation réussie</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="866"/>
      <source>Installation failed</source>
      <translation>L'installation a échoué</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1457"/>
      <source>Confirm remove</source>
      <translation>Confirmer la suppression</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1460"/>
      <source>Are you sure you want to uninstall this Addon?</source>
      <translation>Etes vous sur de désinstaller ce module?</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1513"/>
      <source>Execution of Addon&apos;s uninstall.py script failed. Proceeding with uninstall...</source>
      <translation>L'exécution du script d'Addon&apos;s uninstall.py a échoué. Poursuivre avec la désinstallation...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1558"/>
      <source>Successfully uninstalled {}</source>
      <translation type="unfinished">Successfully uninstalled {}</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="157"/>
      <source>Unable to fetch the code of this macro.</source>
      <translation>Impossible de récupérer le code de cette macro.</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="164"/>
      <source>Unable to retrieve a description for this macro.</source>
      <translation>Impossible de retrouver la description de cette macro.</translation>
    </message>
  </context>
  <context>
    <name>Std_AddonMgr</name>
    <message>
      <location filename="AddonManager.py" line="68"/>
      <source>&amp;Addon manager</source>
      <translation>&amp;Gestionnaire d'Addon</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="69"/>
      <source>Manage external workbenches and macros</source>
      <translation>Gérer les ateliers et macros externes</translation>
    </message>
  </context>
  <context>
    <name>AddonInstaller</name>
    <message>
      <location filename="addonmanager_workers.py" line="535"/>
      <source>Installed location</source>
      <translation>Emplacement installé</translation>
    </message>
  </context>
  <context>
    <name>Dialog</name>
    <message>
      <location filename="../../AddonManager.ui" line="14"/>
      <source>Addon Manager</source>
      <translation>Gestionnaire d'extensions</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="37"/>
      <source>Workbenches</source>
      <translation>Ateliers</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="47"/>
      <source>Macros</source>
      <translation>Macros</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="56"/>
      <source>Executes the selected macro, if installed</source>
      <translation>Exécuter la macro sélectionnée, si elle est installée</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="59"/>
      <source>Execute</source>
      <translation>Lancer</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="89"/>
      <source>Sets configuration options for the Addon Manager</source>
      <translation>Définit les options de configuration pour le gestionnaire d'addon</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="92"/>
      <source>Configure...</source>
      <translation>Configurer...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="113"/>
      <source>Downloading info...</source>
      <translation>Téléchargement des informations...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="127"/>
      <source>Uninstalls a selected macro or workbench</source>
      <translation>Désinstalle une macro ou un atelier sélectionné</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="130"/>
      <source>Uninstall selected</source>
      <translation>Désinstaller la sélection</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="137"/>
      <source>Installs or updates the selected macro or workbench</source>
      <translation>Installe ou met à jour la macro ou l'atelier sélectionnés</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="140"/>
      <source>Install/update selected</source>
      <translation>Installer/mettre à jour la sélection</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="147"/>
      <source>Download and apply all available updates</source>
      <translation>Télécharger et installer toutes les mises à jour disponibles</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="150"/>
      <source>Update all</source>
      <translation>Tout mettre à jour</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="157"/>
      <source>Close the Addon Manager</source>
      <translation>Fermer le Gestionnaire d'Addon</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="160"/>
      <source>Close</source>
      <translation>Fermer</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="14"/>
      <source>Addon manager options</source>
      <translation>Options du gestionnaire d'addon</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="20"/>
      <source>If this option is selected, when launching the Addon Manager,
installed addons will be checked for available updates
(this requires the GitPython package installed on your system)</source>
      <translation>Si cette option est cochée, lors du lancement du gestionnaire de greffons,
les mises à jour disponibles des greffons installés seront vérifiées
(cela nécessite l'installation du paquet GitPython sur votre système)</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="25"/>
      <source>Automatically check for updates at start (requires GitPython)</source>
      <translation>Vérifier automatiquement les mises à jour au démarrage (nécessite GitPython)</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="35"/>
      <source>Custom repositories (one per line):</source>
      <translation>Dépôts personnalisés (un par ligne) :</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="42"/>
      <source>You can use this window to specify additional addon repositories
to be scanned for available addons</source>
      <translation>Vous pouvez utiliser cette fenêtre pour spécifier des répertoires d'addon complémentaires à analyser pour les addons disponibles</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="57"/>
      <source>Proxy </source>
      <translation>Relais </translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="64"/>
      <source>No proxy</source>
      <translation>Aucun relais</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="71"/>
      <source>User system proxy</source>
      <translation>Relais de système utilisateur</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="78"/>
      <source>User defined proxy :</source>
      <translation>Relais défini par l'utilisateur :</translation>
    </message>
  </context>
</TS>
