<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="it" sourcelanguage="en">
  <context>
    <name>AddonsInstaller</name>
    <message>
      <location filename="install_to_toolbar.py" line="76"/>
      <source>Create new toolbar</source>
      <translation>Crea nuova barra degli strumenti</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="219"/>
      <source>A macro installed with the FreeCAD Addon Manager</source>
      <translation>Una macro installata con FreeCAD Addon Manager</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="221"/>
      <source>Run</source>
      <comment>Indicates a macro that can be &apos;run&apos;</comment>
      <translation>Esegui</translation>
    </message>
    <message>
      <location filename="package_details.py" line="112"/>
      <source>Version {version} installed on {date}</source>
      <translation>Versione {version} installata in {date}</translation>
    </message>
    <message>
      <location filename="package_details.py" line="117"/>
      <source>Version {version} installed</source>
      <translation>Versione {version} installata</translation>
    </message>
    <message>
      <location filename="package_details.py" line="121"/>
      <source>Installed on {date}</source>
      <translation>Installato il {date}</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="567"/>
      <source>Installed</source>
      <translation>Installato</translation>
    </message>
    <message>
      <location filename="package_details.py" line="96"/>
      <source>Version</source>
      <translation>Versione</translation>
    </message>
    <message>
      <location filename="package_details.py" line="103"/>
      <source>Unknown version (no package.xml file found)</source>
      <translation>Versione sconosciuta (nessun file package.xml trovato)</translation>
    </message>
    <message>
      <location filename="package_details.py" line="108"/>
      <source>installed on</source>
      <translation>Installato il</translation>
    </message>
    <message>
      <location filename="package_details.py" line="118"/>
      <source>installed</source>
      <translation>installato</translation>
    </message>
    <message>
      <location filename="package_details.py" line="126"/>
      <source>Update available to version</source>
      <translation>Aggiornamento disponibile alla versione</translation>
    </message>
    <message>
      <location filename="package_details.py" line="144"/>
      <source>This is the latest version available</source>
      <translation>Questa è l'ultima versione disponibile</translation>
    </message>
    <message>
      <location filename="package_details.py" line="151"/>
      <source>Updated, please restart FreeCAD to use</source>
      <translation>Aggiornato, riavviare FreeCAD per usare</translation>
    </message>
    <message>
      <location filename="package_details.py" line="159"/>
      <source>Update check in progress</source>
      <translation>Controllo aggiornamento in corso</translation>
    </message>
    <message>
      <location filename="package_details.py" line="163"/>
      <source>Automatic update checks disabled</source>
      <translation>Controllo automatico degli aggiornamenti disabilitato</translation>
    </message>
    <message>
      <location filename="package_details.py" line="172"/>
      <source>Installation location</source>
      <translation>Percorso di installazione</translation>
    </message>
    <message>
      <location filename="package_details.py" line="240"/>
      <source>WARNING: This addon is obsolete</source>
      <translation>ATTENZIONE: Questo addon è obsoleto</translation>
    </message>
    <message>
      <location filename="package_details.py" line="250"/>
      <source>WARNING: This addon is Python 2 Only</source>
      <translation>ATTENZIONE: Questo addon funziona solo con Python 2</translation>
    </message>
    <message>
      <location filename="package_details.py" line="312"/>
      <source>Fetching README.md from package repository</source>
      <translation>Recupero di README.md dal repository del pacchetto</translation>
    </message>
    <message>
      <location filename="package_details.py" line="354"/>
      <source>WARNING: This addon requires FreeCAD </source>
      <translation>ATTENZIONE: Questo addon richiede FreeCAD </translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="431"/>
      <source>Delete cached version of this README and re-download</source>
      <translation>
        <numerusform>Elimina la versione in cache di questo README e ri-scarica</numerusform>
        <numerusform>Elimina la versione in cache di questo README e ri-scarica</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_details.py" line="510"/>
      <source>No URL or wiki page provided by this macro</source>
      <translation>Nessuna pagina URL o wiki fornita da questa macro</translation>
    </message>
    <message>
      <location filename="package_details.py" line="563"/>
      <source>Could not load README data from URL {}</source>
      <translation>Impossibile caricare i dati README dall'URL {}</translation>
    </message>
    <message>
      <location filename="package_details.py" line="577"/>
      <source>Success</source>
      <translation>Operazione riuscita</translation>
    </message>
    <message>
      <location filename="package_details.py" line="600"/>
      <source>Changed to git ref &apos;{}&apos; -- please restart to use Addon.</source>
      <translation>Cambiato in git ref &apos;{}&apos; -- si prega di riavviare per utilizzare Addon.</translation>
    </message>
    <message>
      <location filename="package_details.py" line="636"/>
      <source>Page JavaScript reported</source>
      <translation>JavaScript della pagina segnalato</translation>
    </message>
    <message>
      <location filename="package_details.py" line="407"/>
      <source>Install</source>
      <translation>Installa</translation>
    </message>
    <message>
      <location filename="package_details.py" line="410"/>
      <source>Uninstall</source>
      <translation>Disinstalla</translation>
    </message>
    <message>
      <location filename="package_details.py" line="413"/>
      <source>Update</source>
      <translation>Aggiorna</translation>
    </message>
    <message>
      <location filename="package_details.py" line="416"/>
      <source>Check for Update</source>
      <translation>Controlla aggiornamenti</translation>
    </message>
    <message>
      <location filename="package_details.py" line="419"/>
      <source>Run Macro</source>
      <translation>Esegui macro</translation>
    </message>
    <message>
      <location filename="package_details.py" line="786"/>
      <source>Change Branch</source>
      <translation>Cambia Ramo</translation>
    </message>
    <message>
      <location filename="package_details.py" line="867"/>
      <source>Enable</source>
      <translation>Abilita</translation>
    </message>
    <message>
      <location filename="package_details.py" line="870"/>
      <source>Disable</source>
      <translation>Disabilita</translation>
    </message>
    <message>
      <location filename="package_details.py" line="424"/>
      <source>Return to package list</source>
      <translation>Ritorna alla lista dei pacchetti</translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="800"/>
      <source>QtWebEngine Python bindings not installed -- using fallback README display. See Report View for details and installation instructions.</source>
      <translation type="unfinished">
        <numerusform>QtWebEngine Attacchi Python non installati -- utilizzando il display README di riserva. Vedere il report Visualizza per dettagli e istruzioni di installazione.</numerusform>
        <numerusform>QtWebEngine Python bindings not installed -- using fallback README display. See Report View for details and installation instructions.</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_list.py" line="119"/>
      <source>Filter is valid</source>
      <translation>Il filtro è valido</translation>
    </message>
    <message>
      <location filename="package_list.py" line="125"/>
      <source>Filter regular expression is invalid</source>
      <translation>L'espressione regolare del filtro non è valida</translation>
    </message>
    <message>
      <location filename="package_list.py" line="207"/>
      <source>Click for details about package {}</source>
      <translation>Clicca per i dettagli sul pacchetto {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="211"/>
      <source>Click for details about workbench {}</source>
      <translation>Clicca per i dettagli sull'ambiente di lavoro {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="215"/>
      <source>Click for details about macro {}</source>
      <translation>Clicca per i dettagli sulla macro {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="326"/>
      <source>Maintainer</source>
      <translation>Manutentore</translation>
    </message>
    <message>
      <location filename="package_list.py" line="330"/>
      <source>Maintainers:</source>
      <translation>Manutentori:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="364"/>
      <source>Tags</source>
      <translation>Etichette</translation>
    </message>
    <message>
      <location filename="package_list.py" line="371"/>
      <source>updated</source>
      <translation>aggiornato</translation>
    </message>
    <message>
      <location filename="package_list.py" line="382"/>
      <source>Author</source>
      <translation>Autore</translation>
    </message>
    <message>
      <location filename="package_list.py" line="404"/>
      <source>Up-to-date</source>
      <translation>Aggiornato</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="586"/>
      <source>Update available</source>
      <translation>Aggiornamento disponibile</translation>
    </message>
    <message>
      <location filename="package_list.py" line="414"/>
      <source>Pending restart</source>
      <translation>Riavvio in sospeso</translation>
    </message>
    <message>
      <location filename="package_list.py" line="498"/>
      <source>DISABLED</source>
      <translation>DISABILITATO</translation>
    </message>
    <message>
      <location filename="package_list.py" line="372"/>
      <source>Installed version</source>
      <translation>Versione installata</translation>
    </message>
    <message>
      <location filename="package_list.py" line="180"/>
      <source>Click for details about package</source>
      <translation>Clicca per i dettagli sul pacchetto</translation>
    </message>
    <message>
      <location filename="package_list.py" line="185"/>
      <source>Click for details about workbench</source>
      <translation>Clicca per i dettagli sull'ambiente di lavoro</translation>
    </message>
    <message>
      <location filename="package_list.py" line="190"/>
      <source>Click for details about macro</source>
      <translation>Clicca per i dettagli sulla macro</translation>
    </message>
    <message>
      <location filename="package_list.py" line="376"/>
      <source>Updated</source>
      <translation>Aggiornato</translation>
    </message>
    <message>
      <location filename="package_list.py" line="380"/>
      <source>Unknown version</source>
      <translation>Versione sconosciuta</translation>
    </message>
    <message>
      <location filename="package_list.py" line="383"/>
      <source>Installed on</source>
      <translation>Installato il</translation>
    </message>
    <message>
      <location filename="package_list.py" line="394"/>
      <source>Available version</source>
      <translation>Versione disponibile</translation>
    </message>
    <message>
      <location filename="package_list.py" line="566"/>
      <source>Show Addons containing:</source>
      <translation>Mostra Addons contenente:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="569"/>
      <source>All</source>
      <translation>Tutti</translation>
    </message>
    <message>
      <location filename="package_list.py" line="572"/>
      <source>Workbenches</source>
      <translation>Ambienti di lavoro</translation>
    </message>
    <message>
      <location filename="package_list.py" line="575"/>
      <source>Macros</source>
      <translation>Macro</translation>
    </message>
    <message>
      <location filename="package_list.py" line="578"/>
      <source>Preference Packs</source>
      <translation>Pacchetti preferenze</translation>
    </message>
    <message>
      <location filename="package_list.py" line="692"/>
      <source>Status:</source>
      <translation>Stato:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="695"/>
      <source>Any</source>
      <translation>Qualsiasi</translation>
    </message>
    <message>
      <location filename="package_list.py" line="702"/>
      <source>Not installed</source>
      <translation>Non installato</translation>
    </message>
    <message>
      <location filename="package_list.py" line="582"/>
      <source>Filter</source>
      <translation>Filtro</translation>
    </message>
    <message>
      <location filename="package_list.py" line="585"/>
      <source>OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="115"/>
      <source>Checking network connection...
</source>
      <translation>Controllo connessione di rete...
</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="167"/>
      <source>Unable to download addon list.</source>
      <translation>Impossibile scaricare la lista degli addon.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="172"/>
      <source>Workbenches list was updated.</source>
      <translation>Elenco degli ambienti di lavoro aggiornato.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="261"/>
      <source>Failed loading</source>
      <translation>Caricamento fallito</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="296"/>
      <source>List of macros successfully retrieved.</source>
      <translation>Lista delle macro recuperata con successo.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="310"/>
      <source>GitPython not installed! Cannot retrieve macros from git</source>
      <translation>GitPython non installato! Impossibile recuperare la macro da git</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="319"/>
      <source>Something went wrong with the Git Macro Retrieval, possibly the Git executable is not in the path</source>
      <translation>Qualcosa è andato storto con il recupero della macro da Git, forse l'eseguibile Git non è nel percorso</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="343"/>
      <source>Appears to be an issue connecting to the Wiki, therefore cannot retrieve Wiki macro list at this time</source>
      <translation>Sembra esserci un problema di connessione al Wiki, quindi in questo momento non è possibile recuperare l'elenco delle macro</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="367"/>
      <source>Unable to fetch git updates for workbench</source>
      <translation>Impossibile recuperare gli aggiornamenti git per l'ambiente di lavoro</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="391"/>
      <source>Retrieving info from</source>
      <translation>Recupero informazioni da</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="419"/>
      <source>Failed to read metadata from</source>
      <translation>Lettura dei metadati non riuscita da</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="426"/>
      <source>git fetch failed for {}</source>
      <translation>git fetch fallito per {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="429"/>
      <source>git fetch failed for {wb.name}</source>
      <translation>git fetch fallito per {wb.name}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="433"/>
      <source>Raw markdown displayed</source>
      <translation>Visualizza il sorgente Markdown</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="435"/>
      <source>Python Markdown library is missing.</source>
      <translation>Manca la libreria Python Markdown.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="439"/>
      <source>git pull failed for {wb.name}</source>
      <translation>git pull fallito per {wb.name}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="514"/>
      <source>Done locating macros.</source>
      <translation>Individuazione delle macro completata.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="521"/>
      <source>This addon is already installed.</source>
      <translation>Questo addon è già installato.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="533"/>
      <source>An update is available for this addon.</source>
      <translation>Per questo addon è disponibile un aggiornamento.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="547"/>
      <source>This addon is marked as obsolete</source>
      <translation>Questo addon è contrassegnato come obsoleto</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="551"/>
      <source>This usually means it is no longer maintained, and some more advanced addon in this list provides the same functionality.</source>
      <translation>Questo di solito significa che non è più mantenuto e alcuni addon in questa lista forniscono la stessa funzionalità.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="559"/>
      <source>This addon is marked as Python 2 Only</source>
      <translation>Questo componente aggiuntivo è contrassegnato come solo con Python 2</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="564"/>
      <source>This workbench may no longer be maintained and installing it on a Python 3 system will more than likely result in errors at startup or while in use.</source>
      <translation>Questo ambiente potrebbe non essere più mantenuto e installarlo su un sistema Python 3 causerà probabilmente errori all'avvio o durante l'uso.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="608"/>
      <source>An error occurred fetching macros from GitHub</source>
      <translation>Si è verificato un errore nel recupero delle macro da GitHub</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="646"/>
      <source>An error occurred updating macros from GitHub</source>
      <translation>Si è verificato un errore durante l'aggiornamento delle macro da GitHub</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="651"/>
      <source>Retrieving description...</source>
      <translation>Recupero descrizione...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="665"/>
      <source>This macro is already installed.</source>
      <translation>Questa macro è già installata.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="697"/>
      <source>Caching macro code...</source>
      <translation>Memorizzazione nella cache codice macro...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="700"/>
      <source>GitPython not found. Using standard download instead.</source>
      <translation>GitPython non trovato. In sostituzione, usare il download standard.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="705"/>
      <source>Your version of python doesn&apos;t appear to support ZIP files. Unable to proceed.</source>
      <translation>Sembra che la versione di python non supporti i file ZIP. Impossibile procedere.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="727"/>
      <source>User requested updating a Python 2 workbench on a system running Python 3 - </source>
      <translation>L'utente ha richiesto l'aggiornamento di un ambiente di lavoro in Python 2 su un sistema che esegue Python 3 - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="738"/>
      <source>Outdated GitPython detected, consider upgrading with pip.</source>
      <translation>Rilevato GitPython obsoleto, considerare di aggiornarlo con pip.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="763"/>
      <source>Workbench successfully updated. Please restart FreeCAD to apply the changes.</source>
      <translation>Ambiente di lavoro aggiornato correttamente. Riavviare FreeCAD per applicare le modifiche.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="771"/>
      <source>User requested installing a Python 2 workbench on a system running Python 3 - </source>
      <translation>L'utente ha richiesto l'installazione di un ambiente di lavoro in Python 2 su un sistema che esegue Python 3 - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="786"/>
      <source>Workbench successfully installed. Please restart FreeCAD to apply the changes.</source>
      <translation>Ambiente di lavoro installato correttamente. Riavviare FreeCAD per applicare le modifiche.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="799"/>
      <source>A macro has been installed and is available under Macro -&gt; Macros menu</source>
      <translation>Una macro è stata installata ed è disponibile sotto Macro -&gt; menu Macros</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="824"/>
      <source>Retrieving info from {}</source>
      <translation>Recupero informazioni da {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="835"/>
      <source>Missing workbench</source>
      <translation>Ambiente di lavoro mancante</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="844"/>
      <source>Missing python module</source>
      <translation>Modulo python mancante</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="854"/>
      <source>Missing optional python module (doesn&apos;t prevent installing)</source>
      <translation>Modulo Python opzionale mancante (ma non impedisce l'installazione)</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="857"/>
      <source>Some errors were found that prevent to install this workbench</source>
      <translation>Sono stati trovati alcuni errori che impediscono di installare questo ambiente di lavoro</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="859"/>
      <source>Please install the missing components first.</source>
      <translation>Si prega di installare prima i componenti mancanti.</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="873"/>
      <source>Error: Unable to locate zip from</source>
      <translation>Errore: Impossibile individuare zip da</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="880"/>
      <source>Error: Unable to download</source>
      <translation>Errore: download impossibile</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="893"/>
      <source>Successfully installed</source>
      <translation>Installazione riuscita</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="915"/>
      <source>Retrieving macro description...</source>
      <translation>Recupero descrizione macro...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="653"/>
      <source>Retrieving info from git</source>
      <translation>Recupero informazioni da git</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="656"/>
      <source>Retrieving info from wiki</source>
      <translation>Recupero informazioni dal wiki</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1013"/>
      <source>Error updating module</source>
      <translation>Errore nell'aggiornamento del modulo</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1075"/>
      <source>Error updating module </source>
      <translation>Errore nell'aggiornamento del modulo </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1078"/>
      <source>Please fix manually</source>
      <translation>Correggi manualmente</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1220"/>
      <source>Error: Unable to locate ZIP from</source>
      <translation>Errore: Impossibile individuare zip da</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1403"/>
      <source>Retrieving package metadata...</source>
      <translation>Recupero metadati dei pacchetti...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1405"/>
      <source>Failed to execute pip. Returned error was:</source>
      <translation>Impossibile eseguire pip. Errore restituito era:</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1611"/>
      <source>Downloaded package.xml for {}</source>
      <translation>Pacchetto.xml scaricato per {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1641"/>
      <source>Downloaded metadata.txt for {}</source>
      <translation>Metadati.txt scaricato per {}</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1715"/>
      <source>Downloaded icon for {}</source>
      <translation>Icona scaricata per {}</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="332"/>
      <source>Failed to repair missing .git directory</source>
      <translation>Impossibile riparare la directory .git mancante</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="335"/>
      <source>Repository URL</source>
      <translation>URL del repository</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="338"/>
      <source>Clone directory</source>
      <translation>Clona directory</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="72"/>
      <source>Error with encrypted connection</source>
      <translation>Errore con connessione cifrata</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="135"/>
      <source>Failed to connect to</source>
      <translation>Impossibile connettersi a</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="220"/>
      <source>Failed to connect to URL</source>
      <translation>Impossibile connettersi all'URL</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="101"/>
      <source>DANGER: Developer feature</source>
      <translation>PERICOLO: Funzione per sviluppatore</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="114"/>
      <source>There are local changes</source>
      <translation>Ci sono delle modifiche locali.</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="192"/>
      <source>Branch</source>
      <comment>git terminology</comment>
      <translation>Ramo</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="178"/>
      <source>Tag</source>
      <comment>git terminology</comment>
      <translation type="unfinished">Tag</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="261"/>
      <source>Kind</source>
      <comment>Table header for git ref type (e.g. either Tag or Branch)</comment>
      <translation type="unfinished">
        <numerusform>Tipo</numerusform>
        <numerusform>Kind</numerusform>
      </translation>
    </message>
    <message>
      <location filename="change_branch.py" line="265"/>
      <source>Local name</source>
      <comment>Table header for git ref name</comment>
      <translation>Nome locale</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="271"/>
      <source>Tracking</source>
      <comment>Table header for git remote tracking branch name name</comment>
      <translation type="unfinished">
        <numerusform>Tracciamento</numerusform>
        <numerusform>Tracking</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="277"/>
      <source>Local updated</source>
      <comment>Table header for git update time of local branch</comment>
      <translation type="unfinished">
        <numerusform>Locale aggiornato</numerusform>
        <numerusform>Local updated</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="283"/>
      <source>Remote updated</source>
      <comment>Table header for git update time of remote branch</comment>
      <translation type="unfinished">
        <numerusform>Aggiornato da remoto</numerusform>
        <numerusform>Remote updated</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="191"/>
      <source>Checking connection</source>
      <translation>Controllo connessione</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="192"/>
      <source>Checking for connection to GitHub...</source>
      <translation>Controllo della connessione a GitHub...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="213"/>
      <source>Connection failed</source>
      <translation>Connessione non riuscita</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="240"/>
      <source>Missing dependency</source>
      <translation>Prerequisiti mancanti</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="324"/>
      <source>Starting up...</source>
      <translation>Avvio...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="258"/>
      <source>Loading addon information</source>
      <translation>Caricamento informazioni addon</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="199"/>
      <source>Addon manager</source>
      <translation>Addon manager</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="209"/>
      <source>Restart now</source>
      <translation>Riavvia ora</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="210"/>
      <source>Restart later</source>
      <translation>Riavvia dopo</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1248"/>
      <source>Refresh local cache</source>
      <translation>Aggiorna cache locale</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="659"/>
      <source>Updating cache...</source>
      <translation>Aggiornamento cache...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="766"/>
      <source>Could not find addon &apos;{}&apos; to select
</source>
      <translation>Impossibile trovare l'addon &apos;{}&apos; da selezionare</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="243"/>
      <source>Checking for updates...</source>
      <translation>Controllo aggiornamenti...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="773"/>
      <source>Apply {} update(s)</source>
      <translation>Applica {} aggiornamento(i)</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="577"/>
      <source>No updates available</source>
      <translation>Nessun aggiornamento disponibile</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="915"/>
      <source>Too many to list</source>
      <translation>Troppi da elencare</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="893"/>
      <source>Missing Requirement</source>
      <translation>Requisito Mancante</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="86"/>
      <source>The addons that can be installed here are not officially part of FreeCAD, and are not reviewed by the FreeCAD team. Make sure you know what you are installing!</source>
      <translation>Gli addons che possono essere installati da qui non sono parte ufficiale di FreeCAD e non sono revisionati dal team FreeCAD. Accertarsi di sapere cosa si sta installando!</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="203"/>
      <source>You must restart FreeCAD for changes to take effect.</source>
      <translation>È necessario riavviare FreeCAD perché le modifiche abbiano effetto.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="204"/>
      <source>You must restart FreeCAD for changes to take effect. Press Ok to restart FreeCAD now, or Cancel to restart later.</source>
      <translation>Per rendere effettive le modifiche è necessario riavviare FreeCAD. Premere Ok per riavviare FreeCAD ora, o Annulla per riavviare più tardi.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="241"/>
      <source>Could not import QtNetwork -- see Report View for details. Addon Manager unavailable.</source>
      <translation>Impossibile importare QtNetwork -- vedere Report View per i dettagli. Addon Manager non disponibile.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="262"/>
      <source>Apply</source>
      <translation>Applica</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="263"/>
      <source>update(s)</source>
      <translation>aggiornamento/i</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="266"/>
      <source>No update available</source>
      <translation>Nessun aggiornamento disponibile</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="433"/>
      <source>Macro successfully installed. The macro is now available from the Macros dialog.</source>
      <translation>Macro installata con successo. Ora la macro è disponibile dalla finestra di dialogo Macro.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="435"/>
      <source>Unable to install</source>
      <translation>Impossibile installare</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="494"/>
      <source>Addon successfully removed. Please restart FreeCAD</source>
      <translation>Addon rimosso con successo. Si prega di riavviare FreeCAD</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="496"/>
      <source>Unable to remove this addon</source>
      <translation>Impossibile rimuovere questo addon</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="502"/>
      <source>Macro successfully removed.</source>
      <translation>Macro rimossa con successo.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="504"/>
      <source>Macro could not be removed.</source>
      <translation>Impossibile rimuovere la macro.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="534"/>
      <source>Addon Manager: Skipping update check because AutoCheck user preference is False</source>
      <translation>Addon Manager: Non si esegue il controllo dell'aggiornamento perché la preferenza utente AutoCheck è impostata False</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="542"/>
      <source>Restart required</source>
      <translation>Riavvio richiesto</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="774"/>
      <source>All packages updates failed. Packages:</source>
      <translation>Aggiornamento di tutti i pacchetti fallito. Pacchetti:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="786"/>
      <source>Failed packages:</source>
      <translation>Pacchetti falliti:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1079"/>
      <source>Press OK to install anyway.</source>
      <translation>Premere OK per installare comunque.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="964"/>
      <source>Installing dependencies</source>
      <translation>Installazione delle dipendenze</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1061"/>
      <source>Cannot execute Python</source>
      <translation>Impossibile eseguire Python</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1081"/>
      <source>Cannot execute pip</source>
      <translation>Impossibile eseguire pip</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1102"/>
      <source>Package installation failed</source>
      <translation>Installazione del pacchetto fallita</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1105"/>
      <source>See Report View for detailed failure log.</source>
      <translation>Vedere Report View per il registro di errore dettagliato.</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="703"/>
      <source>Installation of macro failed</source>
      <translation>Installazione della macro fallita</translation>
    </message>
    <message numerus="yes">
      <location filename="AddonManager.py" line="1280"/>
      <source>{} total, see Report view for list</source>
      <comment>Describes the number of updates that were completed (&apos;{}&apos; is replaced by the number of updates)</comment>
      <translation>
        <numerusform>{} totale, vedere Vista report per l'elenco</numerusform>
        <numerusform>{} totale, vedere Vista report per l'elenco</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1178"/>
      <source>Succeeded</source>
      <translation>Riuscito</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1159"/>
      <source>All packages updates failed:</source>
      <translation>Aggiornamento di tutti i pacchetti non riuscito:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1183"/>
      <source>Failed</source>
      <translation>Non riuscito</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="800"/>
      <source>Update report</source>
      <translation>Aggiorna report</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="850"/>
      <source>Installation succeeded</source>
      <translation>Installazione riuscita</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="866"/>
      <source>Installation failed</source>
      <translation>Installazione non riuscita</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1457"/>
      <source>Confirm remove</source>
      <translation>Conferma rimozione</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1460"/>
      <source>Are you sure you want to uninstall this Addon?</source>
      <translation>Sei sicuro di voler disinstallare questo Addon?</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1513"/>
      <source>Execution of Addon&apos;s uninstall.py script failed. Proceeding with uninstall...</source>
      <translation>Esecuzione dello script di Addon&apos;s uninstall.py non riuscita. Proseguire con la disinstallazione...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1558"/>
      <source>Successfully uninstalled {}</source>
      <translation>Disinstallato con successo {}</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="157"/>
      <source>Unable to fetch the code of this macro.</source>
      <translation>Impossibile recuperare il codice di questa macro.</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="164"/>
      <source>Unable to retrieve a description for this macro.</source>
      <translation>Impossibile recuperare una descrizione per questa macro.</translation>
    </message>
  </context>
  <context>
    <name>Std_AddonMgr</name>
    <message>
      <location filename="AddonManager.py" line="68"/>
      <source>&amp;Addon manager</source>
      <translation>&amp;Addon manager</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="69"/>
      <source>Manage external workbenches and macros</source>
      <translation>Gestisce gli ambienti di lavoro e le macro esterne</translation>
    </message>
  </context>
  <context>
    <name>AddonInstaller</name>
    <message>
      <location filename="addonmanager_workers.py" line="535"/>
      <source>Installed location</source>
      <translation>Percorso di installazione</translation>
    </message>
  </context>
  <context>
    <name>Dialog</name>
    <message>
      <location filename="../../AddonManager.ui" line="14"/>
      <source>Addon Manager</source>
      <translation>Addon manager</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="37"/>
      <source>Workbenches</source>
      <translation>Ambienti di lavoro</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="47"/>
      <source>Macros</source>
      <translation>Macro</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="56"/>
      <source>Executes the selected macro, if installed</source>
      <translation>Esegue la macro selezionata, se installata</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="59"/>
      <source>Execute</source>
      <translation>Esegui</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="89"/>
      <source>Sets configuration options for the Addon Manager</source>
      <translation>Imposta le opzioni di configurazione per Addon Manager</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="92"/>
      <source>Configure...</source>
      <translation>Configura...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="113"/>
      <source>Downloading info...</source>
      <translation>Download informazioni...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="127"/>
      <source>Uninstalls a selected macro or workbench</source>
      <translation>Disinstalla un ambiente di lavoro o una macro selezionata</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="130"/>
      <source>Uninstall selected</source>
      <translation>Disinstalla selezionati</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="137"/>
      <source>Installs or updates the selected macro or workbench</source>
      <translation>Installa o aggiorna l'ambiente di lavoro selezionato</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="140"/>
      <source>Install/update selected</source>
      <translation>Installa/aggiorna selezionati</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="147"/>
      <source>Download and apply all available updates</source>
      <translation>Scarica e applica tutti gli aggiornamenti disponibili</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="150"/>
      <source>Update all</source>
      <translation>Aggiorna tutto</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="157"/>
      <source>Close the Addon Manager</source>
      <translation>Chiude Addon manager</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="160"/>
      <source>Close</source>
      <translation>Chiudi</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="14"/>
      <source>Addon manager options</source>
      <translation>Opzioni di Addon manager</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="20"/>
      <source>If this option is selected, when launching the Addon Manager,
installed addons will be checked for available updates
(this requires the GitPython package installed on your system)</source>
      <translation>Se questa opzione è selezionata, quando si avvia Addon Manager,
gli addons installati verranno controllati per gli aggiornamenti disponibili
(questo richiede che il pacchetto GitPython sia installato sul sistema)</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="25"/>
      <source>Automatically check for updates at start (requires GitPython)</source>
      <translation>Controlla automaticamente gli aggiornamenti all'avvio (richiede GitPython)</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="35"/>
      <source>Custom repositories (one per line):</source>
      <translation>Repository personalizzati (uno per riga):</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="42"/>
      <source>You can use this window to specify additional addon repositories
to be scanned for available addons</source>
      <translation>È possibile utilizzare questa finestra per specificare ulteriori repository di addon
da scansionare per gli addon disponibili</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="57"/>
      <source>Proxy </source>
      <translation>Proxy </translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="64"/>
      <source>No proxy</source>
      <translation>No proxy</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="71"/>
      <source>User system proxy</source>
      <translation>Usa il proxy di rete del sistema</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="78"/>
      <source>User defined proxy :</source>
      <translation>Proxy definito dall'utente :</translation>
    </message>
  </context>
</TS>
